apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: krfat-dual-role
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 80Gi
        deleteClaim: false
  resources: # (6)
      requests:
        memory: 64Gi
        cpu: "8"
      limits:
        memory: 64Gi
        cpu: "12"
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 3.7-IV4
    logging: # (3)
      type: inline
      loggers:
        kafka.root.logger.level: INFO
    resources: # (4)
      requests:
        memory: 64Gi
        cpu: "8"
      limits:
        memory: 64Gi
        cpu: "12"
    jvmOptions: # (6)
      -Xms: 8192m
      -Xmx: 8192m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    
    storage: # (19)
      type: persistent-claim # (20)
      size: 10000Gi
    rack: # (21)
      topologyKey: topology.kubernetes.io/zone

  entityOperator:
    topicOperator: {}
    userOperator:
      watchedNamespace: kafka-tfg